apiVersion: v1
kind: Secret
metadata:
  name: ethio-connect-repository
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  name: ethio-connect
  type: git
  url: https://github.com/ethio-connect-ethiopia/ethio-connect.git
