apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: tenant
  namespace: argocd
  labels:
    app.kubernetes.io/name: tenant
    app.kubernetes.io/part-of: ethio-connect
spec:
  description: Tenant Services - Client API and Dashboard
  sourceRepos:
  - https://github.com/ethio-connect-ethiopia/ethio-connect-infrastructure.git
  - https://github.com/ethio-connect-ethiopia/ethio-connect.git
  destinations:
  - namespace: ethio-connect-tenant
    server: https://kubernetes.default.svc
  - namespace: ethio-connect-central
    server: https://kubernetes.default.svc
  clusterResourceWhitelist:
  - group: ""
    kind: Namespace
  - group: ""
    kind: ResourceQuota
  - group: networking.k8s.io
    kind: NetworkPolicy
  namespaceResourceWhitelist:
  - group: "*"
    kind: "*"
  roles:
  - name: tenant-admin
    description: Tenant project admin
    policies:
    - p, role:tenant-admin, tenant-services, *, */*, allow
    - p, role:tenant-admin, applications, *, */*, allow
    groups:
    - tenant-team@ethioconnect.et
  - name: tenant-developer
    description: Tenant developer
    policies:
    - p, role:tenant-developer, tenant-services, get, create, update, */*, allow
    - p, role:tenant-developer, applications, get, *, */*, allow
    groups:
    - developers@ethioconnect.et
