apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - platform-core-appset.yaml
  - workloads-appset.yaml
  - appproject-platform.yaml
  - appproject-central.yaml
  - appproject-provider.yaml
  - appproject-tenant.yaml
  - appproject-public.yaml
