apiVersion: v2
name: ethio-connect-app
description: Helm chart for deploying Ethio Connect application workloads to bare-metal Kubernetes
type: application
version: 0.1.0
appVersion: "1.0.0"
icon: https://raw.githubusercontent.com/ethio-connect-ethiopia/ethio-connect/main/apps/central/central-hub-api/src/assets/logo/symbol.png
