apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: central-hub-api
  namespace: argocd
  labels:
    app.kubernetes.io/name: central-hub-api
    ethio-connect/project: central
spec:
  generators:
  - git:
      repoURL: https://github.com/ethio-connect-ethiopia/ethio-connect-infrastructure.git
      revision: HEAD
      directories:
      - path: environments/testing/apps
      - path: environments/staging/apps
      - path: environments/prod/apps
  template:
    metadata:
      name: "central-hub-api-{{path.basename}}"
    spec:
      project: central
      source:
        repoURL: https://github.com/ethio-connect-ethiopia/ethio-connect-infrastructure.git
        targetRevision: HEAD
        path: "environments/{{path.basename}}/apps/central-hub-api.yaml"
      destination:
        server: https://kubernetes.default.svc
        namespace: ethio-connect-central
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
        - CreateNamespace=true
