apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: vendor-services
  namespace: argocd
  labels:
    app.kubernetes.io/name: vendor-services
    ethio-connect/project: provider
spec:
  generators:
  - list:
      elements:
      - env: testing
        app: api-server
        path: environments/testing/apps/vendor-api-server.yaml
      - env: testing
        app: web-dashboard
        path: environments/testing/apps/vendor-web-dashboard.yaml
      - env: staging
        app: api-server
        path: environments/staging/apps/vendor-api-server.yaml
      - env: staging
        app: web-dashboard
        path: environments/staging/apps/vendor-web-dashboard.yaml
      - env: prod
        app: api-server
        path: environments/prod/apps/vendor-api-server.yaml
      - env: prod
        app: web-dashboard
        path: environments/prod/apps/vendor-web-dashboard.yaml
  template:
    metadata:
      name: "vendor-{{env}}-{{app}}"
    spec:
      project: provider
      sources:
      - chart: ethio-connect-app
        repoURL: https://github.com/ethio-connect-ethiopia/ethio-connect-infrastructure.git
        targetRevision: "0.1.0"
        helm:
          valueFiles:
          - "{{path}}"
      destination:
        server: https://kubernetes.default.svc
        namespace: ethio-connect-provider
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
        - CreateNamespace=true
