apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: vendor-services
  namespace: argocd
  labels:
    app.kubernetes.io/name: vendor-services
    ethio-connect/project: provider
spec:
  generators:
  - git:
      repoURL: https://github.com/ethio-connect-ethiopia/ethio-connect-infrastructure.git
      revision: HEAD
      files:
      - path: environments/testing/apps/vendor-api-server.yaml
      - path: environments/testing/apps/vendor-web-dashboard.yaml
      - path: environments/staging/apps/vendor-api-server.yaml
      - path: environments/staging/apps/vendor-web-dashboard.yaml
      - path: environments/prod/apps/vendor-api-server.yaml
      - path: environments/prod/apps/vendor-web-dashboard.yaml
  template:
    metadata:
      name: "vendor-{{path.basename}}"
    spec:
      project: provider
      source:
        repoURL: https://github.com/ethio-connect-ethiopia/ethio-connect-infrastructure.git
        targetRevision: HEAD
        path: "{{path}}"
      destination:
        server: https://kubernetes.default.svc
        namespace: ethio-connect-provider
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
        - CreateNamespace=true
