apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: public-website
  namespace: argocd
  labels:
    app.kubernetes.io/name: public-website
    ethio-connect/project: public
spec:
  generators:
  - git:
      repoURL: https://github.com/ethio-connect-ethiopia/ethio-connect-infrastructure.git
      revision: HEAD
      files:
      - path: environments/testing/apps/public-website.yaml
      - path: environments/staging/apps/public-website.yaml
      - path: environments/prod/apps/public-website.yaml
  template:
    metadata:
      name: "public-website-{{path.basename}}"
    spec:
      project: public
      source:
        repoURL: https://github.com/ethio-connect-ethiopia/ethio-connect-infrastructure.git
        targetRevision: HEAD
        path: "{{path}}"
      destination:
        server: https://kubernetes.default.svc
        namespace: ethio-connect-public
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
        - CreateNamespace=true
