apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: client-services
  namespace: argocd
  labels:
    app.kubernetes.io/name: client-services
    ethio-connect/project: tenant
spec:
  generators:
  - git:
      repoURL: https://github.com/ethio-connect-ethiopia/ethio-connect-infrastructure.git
      revision: HEAD
      directories:
      - path: environments/*/apps/client-*.yaml
  template:
    metadata:
      name: "{{path.basename}}-{{path[0]}}"
    spec:
      project: tenant
      source:
        repoURL: https://github.com/ethio-connect-ethiopia/ethio-connect-infrastructure.git
        targetRevision: HEAD
        path: "{{path.path}}"
      destination:
        server: https://kubernetes.default.svc
        namespace: ethio-connect-tenant
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
        - CreateNamespace=true
