image:
  repository: ghcr.io/ethio-connect-ethiopia
  tag: "development"
  pullPolicy: IfNotPresent

ingress:
  hosts:
    - host: dev-hub-api.ethioconnect.et
      paths:
        - path: /
          pathType: Prefix
  tls:
    - secretName: ethioconnect-et-wildcard-tls
      hosts:
        - dev-hub-api.ethioconnect.et

resources:
  requests:
    cpu: 150m
    memory: 192Mi
  limits:
    cpu: 400m
    memory: 384Mi
