image:
  repository: ghcr.io/primewale/central-hub-api
  tag: "testing-b7e6092a569c"
  pullPolicy: IfNotPresent

ingress:
  hosts:
    - host: testing-hub-api.ethioconnect.et
      paths:
        - path: /
          pathType: Prefix
  tls:
    - secretName: ethioconnect-et-wildcard-tls
      hosts:
        - testing-hub-api.ethioconnect.et

resources:
  requests:
    cpu: 50m
    memory: 64Mi
  limits:
    cpu: 200m
    memory: 256Mi
