apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: ethio-connect-runtime-secrets
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: platform-secrets
  target:
    name: ethio-connect-runtime-secrets
    creationPolicy: Owner
    template:
      type: Opaque
  data:
    - secretKey: DB_EC_USER
      remoteRef:
        key: ethio-connect/runtime
        property: DB_EC_USER
    - secretKey: DB_EC_PASS
      remoteRef:
        key: ethio-connect/runtime
        property: DB_EC_PASS
    - secretKey: DB_MOR_USER
      remoteRef:
        key: ethio-connect/runtime
        property: DB_MOR_USER
    - secretKey: DB_MOR_PASS
      remoteRef:
        key: ethio-connect/runtime
        property: DB_MOR_PASS
    - secretKey: SESSION_SECRET
      remoteRef:
        key: ethio-connect/runtime
        property: SESSION_SECRET
    - secretKey: NEXTAUTH_SECRET
      remoteRef:
        key: ethio-connect/runtime
        property: NEXTAUTH_SECRET
    - secretKey: JWT_SECRET
      remoteRef:
        key: ethio-connect/runtime
        property: JWT_SECRET
    - secretKey: JWT_ACCESS_SECRET
      remoteRef:
        key: ethio-connect/runtime
        property: JWT_ACCESS_SECRET
    - secretKey: JWT_REFRESH_SECRET
      remoteRef:
        key: ethio-connect/runtime
        property: JWT_REFRESH_SECRET
    - secretKey: SERVICE_AUTH_JWT_SECRET
      remoteRef:
        key: ethio-connect/runtime
        property: SERVICE_AUTH_JWT_SECRET
    - secretKey: COOKIE_PARSER_SECRET
      remoteRef:
        key: ethio-connect/runtime
        property: COOKIE_PARSER_SECRET
    - secretKey: CSRF_SECRET
      remoteRef:
        key: ethio-connect/runtime
        property: CSRF_SECRET
    - secretKey: DB_REDIS_PASSWORD
      remoteRef:
        key: ethio-connect/runtime
        property: DB_REDIS_PASSWORD
    - secretKey: USER_PASSWORD
      remoteRef:
        key: ethio-connect/runtime
        property: USER_PASSWORD
    - secretKey: SENTRY_DSN
      remoteRef:
        key: ethio-connect/runtime
        property: SENTRY_DSN
    - secretKey: VENDOR_API_SERVICE_CLIENT_SECRET
      remoteRef:
        key: ethio-connect/runtime
        property: VENDOR_API_SERVICE_CLIENT_SECRET
    - secretKey: CLIENT_API_SERVICE_CLIENT_SECRET
      remoteRef:
        key: ethio-connect/runtime
        property: CLIENT_API_SERVICE_CLIENT_SECRET
